# Site settings
title: Torrin Fields Portfolio
description: "Torrin Fields' professional portfolio"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tfields77.github.io" # the base hostname & protocol for your site

# Author settings
author:
  name: Torrin Fields
  email: Torrin.a.fieldsl@example.com
  social:
    github: tfields77
    linkedin: https://www.linkedin.com/in/torrin-fields-336a42255/
    twitter: your-twitter-handle

# Build settings
markdown: kramdown
theme: minima # Choose a theme that suits your design, 'minima' is a simple one
plugins:
  - jekyll-feed
  - jekyll-seo-tag



# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby

# Optional settings
paginate: 5
paginate_path: "/page:num/"



# Google Analytics
google_analytics: UA-XXXXXXXX-X


